# Verified working with rootfull docker (run with sudo docker compose up -d)

services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped

    # Networking
    ports:
      - 8080:8080 # SABnzbd
      - 9696:9696 # Prowlarr
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
      - 6767:6767 # Bazarr

    # Filesystem
    volumes:
      - ./config:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    
    # Security
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
      
    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}
      SERVER_CITIES: ${SERVER_CITIES}
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY} # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/mullvad.md
      WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES}
      UPDATER_PERIOD: 24h
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

    

    
