services:
  prometheus_node_exporter:
    image: quay.io/prometheus/node-exporter:v1.8.2
    container_name: prometheus_node_exporter
    ports:
      - 9100:9100
    command: "--path.rootfs=/host"
    pid: host
    restart: always
    volumes:
      - /:/host:ro,rslave
