authentik:
    secret_key: ENC[AES256_GCM,data:GW4R+Gw6bwR1U+B1yT2iYPSn3BJGgwF2dQXU4Q8EEl0z0ryd5yyEJVU=,iv:cHFUt4LT2uYk2reDDNEsGaMXddUpPkzAQf76CkhRv3I=,tag:dtMJn/JoLlDIjo5TePn5Cw==,type:str]
sops:
    age:
        - recipient: age1tneafc8h2ad3lmcvway7h5mrralurtuddqaahe3pz9jyhyhs7qxq5kjed7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeldEcEJ6NjFxQmRuVFB2
            eXp2RWtvZWY2S0VDcmtxREY2RmYxREs0aDE0CnpHemVob0g4RndqWTdNdjZnRnR4
            VWM1Tk45emJRa0V5WHVyZXpoNUp6VzgKLS0tIHMyQXRMVXRwYmdxK2xDVERmTlFj
            TDNTeExUdFlwQzRmdTNlcFEwY244Y00KJb5fgI71Vtd4SnHkaO2ESc5HjNwPF1f7
            3R8j96vhwBXPHvKUZ0kj0+3vT3W4XOGUgq/4jTtkgKUbcDlw+1mYnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T16:20:20Z"
    mac: ENC[AES256_GCM,data:KBeGQ7vwaiJl9IwMmP/zH7Dh6BHlvTabqWJnoIgZPygUj97zcVH1O7LMXrd9/htY4XJJ+TJkOR0wfchB5piy+MRM8cPnk4wK3sDJcRcmQ95gERU2oqS6l9g462oJH0RRMvA1tvtXr2geSaMIvwJ9Sx9WkCXYJs2QIof0DMbSQqM=,iv:j3DpOU07gFa0T98V/v0mZa7KL9y9bICcN1SlV5e77SQ=,tag:EzC4dq4AONu4CkJekr9zmw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
