services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/images
      - ./icons:/app/icons
    environment:
      PUID: 1000
      PGID: 1000
      HOMEPAGE_VAR_PROXMOX_API_USERNAME: ${HOMEPAGE_VAR_PROXMOX_API_USERNAME}
      HOMEPAGE_VAR_PROXMOX_API_PASSWORD: ${HOMEPAGE_VAR_PROXMOX_API_PASSWORD}
      HOMEPAGE_VAR_QBITTORRENT_USERNAME: ${HOMEPAGE_VAR_QBITTORRENT_USERNAME}
      HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ${HOMEPAGE_VAR_QBITTORRENT_PASSWORD}
      HOMEPAGE_VAR_PIHOLE_API: ${HOMEPAGE_VAR_PIHOLE_API}
      HOMEPAGE_VAR_AUTHENTIK_API: ${HOMEPAGE_VAR_AUTHENTIK_API}
      HOMEPAGE_VAR_UNIFI_USERNAME: ${HOMEPAGE_VAR_UNIFI_USERNAME}
      HOMEPAGE_VAR_UNIFI_PASSWORD: ${HOMEPAGE_VAR_UNIFI_PASSWORD}
    restart: unless-stopped
