{
 "title": "Proxmox host",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "GPU Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp1\", chip=\"wmi_bus_pnp0c14:02_466747a0_70ec_11de_8a39_0800200c9a66\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{gpu=\"0\"}",
     "legendFormat": "RTX 4060TI 16GB"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp1\", chip=\"wmi_bus_pnp0c14:02_466747a0_70ec_11de_8a39_0800200c9a66\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{gpu=\"0\"}",
     "legendFormat": "RTX 4060TI 16GB"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VRAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{gpu=\"0\"}",
     "legendFormat": "RTX 4060TI 16GB"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_Active_bytes", "legendFormat": "Proxmox RAM" }
   ]
  },
  {
   "title": "Fans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{sensor=\"fan1\"}",
     "legendFormat": "CPU Fan"
    },
    {
     "expr": "node_hwmon_fan_rpm{sensor=\"fan2\"}",
     "legendFormat": "Chassi Exhaust Fan"
    },
    {
     "expr": "node_hwmon_fan_rpm{sensor=\"fan3\"}",
     "legendFormat": "Chassi Intake Fans"
    },
    {
     "expr": "node_hwmon_fan_rpm{sensor=\"fan4\"}",
     "legendFormat": "fan4"
    },
    {
     "expr": "node_hwmon_fan_rpm{sensor=\"fan7\"}",
     "legendFormat": "fan7"
    }
   ]
  }
 ]
}