appSecrets:
    authentik:
        password: ENC[AES256_GCM,data:TQGypRXhkhDiQXMfVkW6l2jWWFtRu65w5KLPrRvhtOGyBch8JtS9yI+LFICvYZ6/FWEXx+toSGGAcOmR,iv:JACMx7bcx+PP+Xk7hihWox8wlvWmvfgeeDG44Za8zTM=,tag:6K3znWzQYCodhDIZxDnzJw==,type:str]
sops:
    age:
        - recipient: age1tneafc8h2ad3lmcvway7h5mrralurtuddqaahe3pz9jyhyhs7qxq5kjed7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSS1dQM3h4T2RRWUNadDZj
            cWRZMkVRR1JpU2Q4N0xxL1dHUTRjMStaQ3hrCkEvdElhQXlzWXdIUVN4ajFEQ2Fu
            MmVManhweFRCRHRWU2V3MjJCMXRIUUUKLS0tIHRTRkw0SHZweGdlWE5zUE9LNXY2
            bVQ5MWcxcUREM0VGR3RrckFYZWErNDgKXqTPS8maWDZ2eQMUbDhMQLD/81qRwfVe
            ogyZZptZfD+ySIcLdMOoJ/GIcO2jS3mdlInE9vSx7HUZQmRm75aeYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T09:59:01Z"
    mac: ENC[AES256_GCM,data:KkfCCHEhAxzNk2PzjtJvng9RsXVmZhGOYkSvy5PvDFtZ5oiIwx9IdDlpPEenKQCdhQEraJyQWdzx7JliezTGghLUecTv9gss2O/+STPO7jpFFfNTiVcBhLPpppCuMPMLpx0XxcDJWW4LEVbgWAgksLX2GEdtFsrKOlhdFV2N4SU=,iv:r+hOKj59PL4xsER/Ln8AEy+f5w6UsGzLg5iihVLJdeM=,tag:QZpgzGz3RXAL1RcwBgHJuA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
