appSecrets:
    authentik:
        password: ENC[AES256_GCM,data:OIoqmrRTI9rtKLOHX0uPysu3vfYEVjJLZxMlQG08pNI45mqaQgzlNmY3StM=,iv:gXZfaWNJ1BSjC7YafGPsWV8RxA0IWmARP9UTGUaA1NA=,tag:b0Jj9cYlnbzbco2novRJQQ==,type:str]
sops:
    age:
        - recipient: age1tneafc8h2ad3lmcvway7h5mrralurtuddqaahe3pz9jyhyhs7qxq5kjed7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSS1dQM3h4T2RRWUNadDZj
            cWRZMkVRR1JpU2Q4N0xxL1dHUTRjMStaQ3hrCkEvdElhQXlzWXdIUVN4ajFEQ2Fu
            MmVManhweFRCRHRWU2V3MjJCMXRIUUUKLS0tIHRTRkw0SHZweGdlWE5zUE9LNXY2
            bVQ5MWcxcUREM0VGR3RrckFYZWErNDgKXqTPS8maWDZ2eQMUbDhMQLD/81qRwfVe
            ogyZZptZfD+ySIcLdMOoJ/GIcO2jS3mdlInE9vSx7HUZQmRm75aeYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T16:40:00Z"
    mac: ENC[AES256_GCM,data:tA08LSK2lBbARa5NC8Enl3bYm/JmFHjErWLbS+dK3GL6RnCxHtUdCQy+wcdrNobY7sIyHuzrSq/QEG0mEnn1o8aavqLNE84AM9zPocP3kH0jv2rYN5uD6xVvzuHeIzthu1QhiEc/dl6xF9FtY4vUEep0qQoJ1LSryNWdMxdAe4c=,iv:Fk3LX8Q3nM6bqx3xqZZZjBKS/jS4Zb4AxSM69AV8ROE=,tag:+DbnnX1FG2v0dOonRgPvIw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
