services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:v1.12.3
    restart: unless-stopped
    ports:
      - 127.0.0.1:3001:3000
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: ${TIMEZONE:-Europe/Stockholm}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      LOG_TARGETS: stdout
      HOMEPAGE_ALLOWED_HOSTS: homepage.local.jabbas.dev,127.0.0.1:3001,localhost:3001
      HOMEPAGE_VAR_HOMEASSISTANT_API: ${HOMEPAGE_VAR_HOMEASSISTANT_API:-}
    volumes:
      - ./config:/app/config
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
