secret:
  create: true
  name: homepage-secrets
  env:
    HOMEPAGE_VAR_AUTHENTIK_API: change-me
    HOMEPAGE_VAR_BAZARR_API: change-me
    HOMEPAGE_VAR_HOMEASSISTANT_API: change-me
    HOMEPAGE_VAR_JELLYFIN_API: change-me
    HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY: change-me
    HOMEPAGE_VAR_PIHOLE_PASSWORD: change-me
    HOMEPAGE_VAR_PROWLARR_API: change-me
    HOMEPAGE_VAR_PROXMOX_API_PASSWORD: change-me
    HOMEPAGE_VAR_PROXMOX_API_USERNAME: change-me
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: change-me
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: change-me
    HOMEPAGE_VAR_RADARR_API: change-me
    HOMEPAGE_VAR_READARR_API: change-me
    HOMEPAGE_VAR_SABNZBD_API_KEY: change-me
    HOMEPAGE_VAR_SONARR_API: change-me
    HOMEPAGE_VAR_TRUENAS_API: change-me
    HOMEPAGE_VAR_UNIFI_PASSWORD: change-me
    HOMEPAGE_VAR_UNIFI_USERNAME: change-me
    HOMEPAGE_VAR_WEATHERAPI_API_KEY: change-me
