secret:
    create: ENC[AES256_GCM,data:V5I6gw==,iv:MnkIVKfDQiLBKtzrVhzwb00XcZx8zYyQS/6tWjpNdwg=,tag:ekIVi6NXqf03/ZImFtmM8A==,type:bool]
    name: ENC[AES256_GCM,data:FU8LsJo5UkyvB07zu895gg==,iv:gDBvNTEuKpy67HPjp5bmrWQ9A3aujU4v7zjaYob2F6M=,tag:BeUdqC+CPDbEU4tKPJLisw==,type:str]
    env:
        HOMEPAGE_VAR_AUTHENTIK_API: ENC[AES256_GCM,data:h4eSlg==,iv:8NoHwX8u5KWRsKACUsmvpHHCxngn3/G+V7qGfc1zoOY=,tag:SPX6+0iHMczfP1KGv8agWQ==,type:str]
        HOMEPAGE_VAR_BAZARR_API: ENC[AES256_GCM,data:3fAOvc2vesvt,iv:OYeEigcxlUK4hTzjfIzKkE/EYLTTJI6Z3pkwdQeGsTU=,tag:N8BBTgDPEnOCGCaz42decg==,type:str]
        HOMEPAGE_VAR_HOMEASSISTANT_API: ENC[AES256_GCM,data:9kz75VvfhbBK,iv:5sQ/Zt+22/CnYVCKYe8rYmDEVjEcreiJBBQuCWzlEFs=,tag:Wx4pciK1RsCzFBeXOLKDXA==,type:str]
        HOMEPAGE_VAR_JELLYFIN_API: ENC[AES256_GCM,data:mJgt9D3ZZLq2,iv:kjvEYRjwuA2n8EIIX4KQzXRSoNjdfPySwceCJ5Hp0MI=,tag:90xecxrTSlvz/gloWSI1CQ==,type:str]
        HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY: ENC[AES256_GCM,data:xB4N9ZTDnhLM,iv:odsMWYpKJQTn1nWwgiH2OSq4PTTGMC8EPNAxJG8bzIU=,tag:Hcq//HM4GpnUKg6DM5h0Eg==,type:str]
        HOMEPAGE_VAR_PIHOLE_API: ENC[AES256_GCM,data:yi7NXz1diVPf,iv:RJ9B2Ak2IdbCpmGnSW/6EdcHiU6aoSiL876ujdH/fNE=,tag:Qd1ulOZNROeSYzB7J1Cp2A==,type:str]
        HOMEPAGE_VAR_PROWLARR_API: ENC[AES256_GCM,data:saYOlKTTrKSN,iv:uKOt03P3iCOJYXS0BwDsavV/hmzbUwzocKLTviHWNdg=,tag:vJhjXKWvQXpUoJNdjtQUig==,type:str]
        HOMEPAGE_VAR_PROXMOX_API_PASSWORD: ENC[AES256_GCM,data:zFOCQKG4hqA/,iv:vBgRiEiGlFCmQ8TXvBY7yN962OjDROb+R9PZi0ZCGek=,tag:7ouoY0Mgz4Pqdf9FkTZzAQ==,type:str]
        HOMEPAGE_VAR_PROXMOX_API_USERNAME: ENC[AES256_GCM,data:t1z8hGQwuMCx,iv:Rkq06wa4CKAtEXMebiiHsmmewhJEPbE8iZhoxCxDR6U=,tag:/SscuTZ6fKU6+XD1lvCbVg==,type:str]
        HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:xfXMbtIS/She,iv:79aGFdvqGGeScXvo5TG28gfK2RjiwMrCndKG0NDXUE4=,tag:8qeViq8bHk5E20oQVjoE7g==,type:str]
        HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:MNNUlzCyEvKu,iv:DEU2lZkUxpQMWh4tJYX0Dj7dLygYc1jfE7EIuPRb5uo=,tag:l1E3RH/xyzMHq6p4E7+RCQ==,type:str]
        HOMEPAGE_VAR_RADARR_API: ENC[AES256_GCM,data:ZB022G7UUSgM,iv:p5A6NamtCzLRixMrGjNVHcIjMAQYgiJhk1v7FcJbZPY=,tag:lFYQ2UWnMAjGKAgVTe7GZw==,type:str]
        HOMEPAGE_VAR_READARR_API: ENC[AES256_GCM,data:h0+3G386wLtY,iv:20Acvv2yo+v8meA7iZPyRb21JwvM+23f8uXZoXsjDfY=,tag:HBM6meKHNf+279nJEXlW5Q==,type:str]
        HOMEPAGE_VAR_SABNZBD_API_KEY: ENC[AES256_GCM,data:GWpRTJaixbo6,iv:MKqxO2R8WYsaH0sTjEO0ab+f9sgKfo6Z+u92eI+Ku6E=,tag:HXRAJElj2mLmQbPf6i6Tqg==,type:str]
        HOMEPAGE_VAR_SONARR_API: ENC[AES256_GCM,data:hazb3gQtrNy5,iv:5fosOlk/sILsQwQ99S/jdBOf6iLyOPuKEcqd7fz8ZX0=,tag:AjIdisitPrUqBhv+IxsN/g==,type:str]
        HOMEPAGE_VAR_TRUENAS_API: ENC[AES256_GCM,data:5w4FMYlTpZCD,iv:SaUh15ReUxjpW4jT/YHvIau3Vb+sc9p+SypYLw06YuY=,tag:oQIZyi8G0/YzUgI37TO6XQ==,type:str]
        HOMEPAGE_VAR_UNIFI_PASSWORD: ENC[AES256_GCM,data:BLB5uV7pJYKt,iv:fAhF3vF/mpvvkgvjtA/SjL/gbURBaMp4hJ2CzzH5pQc=,tag:JTWPZWP92BJtWsw03Tbaig==,type:str]
        HOMEPAGE_VAR_UNIFI_USERNAME: ENC[AES256_GCM,data:Sdi07kXevny2,iv:m/16iyjAYaxCsYkQyV17s00GgYYTTj4iYBS+N4ZBXw8=,tag:qs3O7aMZHqQx0qn6MRRZuw==,type:str]
        HOMEPAGE_VAR_WEATHERAPI_API_KEY: ENC[AES256_GCM,data:XduMmu9Vzl6J,iv:D8pTz3dagDtgyVPCY8bWdNh3Z63UKT61N/biU1BZrTA=,tag:O4LlrfDTGsvV1P+4C4keDg==,type:str]
sops:
    age:
        - recipient: age1tneafc8h2ad3lmcvway7h5mrralurtuddqaahe3pz9jyhyhs7qxq5kjed7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueGdZTENkdmY2UHVyRHZp
            dG1pT2c5WWdaNVJMSkI4ZHBldUVvSTNnMUdrClN3bXhLUlZtNUVGZUNnUnRmVWw4
            TStQelNuRzdJd2pWc1pZeVE0eGRlRTgKLS0tIEZqSGt1Z1ZJVjJLby96UmhhcE1U
            S3JPMThOa0pMTWFVaUhFTlQ0d3Q4eGsKQHtyg/YZhW+wIvCimsCeQvCJPfaWnaqr
            W7qJD/K976umBBP2mwp4ds4c/i81zTa9eh2vpuzaXlpSX1v9rXYh1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T09:22:02Z"
    mac: ENC[AES256_GCM,data:ZWF26j4WZ1havGUFA8mnJF331or3P/SYpT4q7ZpSn5qdE7aJpw/7CrVOiqCF8yiO3lCWqQs94jzh6zD+SRngsJQqnozp7o/WZ/rRKtufhFAgi83kilt7mPaJPpCp1Z2faexg31UU6DJ9jYwLSenLxTZShTpUdZ/Oi3yZnkbVET8=,iv:+zakw9myeYsoX3jJZTcCnAHEYIfZhYNO792OmSUnI/k=,tag:JY+x30Lvt4lgru+Tth0LPA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
