{{- range .Values.externalRoutes }}
{{- if or (not (hasKey . "enabled")) .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | quote }}
  namespace: infra
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  type: ClusterIP
  ports:
    - name: web
      port: {{ .port }}
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ printf "%s-external" .name | quote }}
  namespace: infra
  labels:
    kubernetes.io/service-name: {{ .name | quote }}
    endpointslice.kubernetes.io/managed-by: homelab.jabbas.dev/traefik-resources
  annotations:
    argocd.argoproj.io/sync-wave: "5"
addressType: IPv4
endpoints:
  - addresses:
      - {{ .address | quote }}
ports:
  - name: web
    protocol: TCP
    port: {{ .port }}
{{- end }}
{{- end }}
