services:  
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped

    # Networking
    ports:
      - 8081:8080
    
    # Filesystem
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./searxng:/etc/searxng

    # Security
    cap_drop:
      - ALL                      # drop all Linux capabilities
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation

    # Environment
    environment:
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      SEARXNG_BASE_URL: ${SEARXNG_BASE_URL}
      UWSGI_WORKERS: ${SEARXNG_UWSGI_WORKERS:-4}
      UWSGI_THREADS: ${SEARXNG_UWSGI_THREADS:-4}
