services:  
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped

    # Networking
    ports:
      - 8081:8080
    networks:
      - searxng

    # Filesystem
    volumes:
      - ./searxng:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw

    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation

    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      SEARXNG_BASE_URL: https://${SEARXNG_HOSTNAME}/

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"



  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped

    # Networking
    networks:
      - searxng

    # Filesystem
    volumes:
      - valkey-data:/data
    
    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation
    
    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

networks:
  searxng: