---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Developer:
    - Github:
        - icon: github.png
          href: https://github.com/py-er

- Social:
    - Reddit:
        - icon: linkedin.png
          href: https://www.linkedin.com/in/jacob-bengtsson/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
