---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Developer:
    - Github:
        - icon: github-light.png
          href: https://github.com/py-er
    - Cloudflare:
        - icon: cloudflare.png
          href: https://dash.cloudflare.com
    - Hetzner:
        - icon: hetzner.png
          href: https://console.hetzner.cloud
    - Heroku:
        - icon: heroku.png
          href: https://dashboard.heroku.com
    - Vultr:
        - icon: vultr.png
          href: https://my.vultr.com
    - Namecheap:
        - icon: si-namecheap-#f76809
          href: https://ap.www.namecheap.com

- Social:
    - Linkedin:
        - icon: linkedin.png
          href: https://linkedin.com/in/jacob-bengtsson/

- Slack:
    - Notifications:
      - icon: slack.png
        href: https://app.slack.com/client/T07FCNTJSN6/C07G1GW6UMN