---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

## Broken
# - logo:
#     image: /icons/logos/jabba.png
#     target: _self

- search:
    provider: duckduckgo
    target: _self

- datetime:
    text_size: xl
    format:
        timeStyle: short
        hourCycle: h23