services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:10.11.8@sha256:ae1ac3d89b8598f31f5e1dc5aff898e13eab617303db58f84956e26f7b78c198
    restart: unless-stopped

    # Networking
    ports:
      - 8096:8096 # HTTP

    # Filesystem
    volumes:
      - jellyfin_config:/config
      - /mnt/data/media/tv:/data/tvshows
      - /mnt/data/media/movies:/data/movies
    
    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation

    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

volumes:
  jellyfin_config: