services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    environment:
      - CF_TOKEN: ${CF_TOKEN}
    command: tunnel --no-autoupdate run --token $CF_TOKEN
    restart: always
