apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: infra
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: grafana
      targetRevision: 11.6.1
      helm:
        releaseName: grafana
        valueFiles:
          - $values/machines/stratton/k8s/workloads/infra/grafana/values.yaml
    - repoURL: https://github.com/jabb4/home-server.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/jabb4/home-server.git
      targetRevision: main
      path: machines/stratton/k8s/workloads/infra/grafana/resources
      helm:
        releaseName: grafana-resources
        valueFiles:
          - secrets://secrets.sops.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
