adminPassword: ENC[AES256_GCM,data:6IVqp6fbPPr3Apyes/TqNlo9zdP+nW43,iv:u+p3uYkmjM3/mayyZn1NRONpMyci7fldC8Kfb6paypw=,tag:yNJfaff7sKVzBD4py4P1Tw==,type:str]
sops:
    age:
        - recipient: age1tneafc8h2ad3lmcvway7h5mrralurtuddqaahe3pz9jyhyhs7qxq5kjed7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UlpoenF5SS8ydHhNcGU2
            dG5GeWxhSDAxaFRyT280UkFMSERkM1ZjemhJCnVhQjlvbi9pZ3VocGE2UXlBV1ZZ
            YjN4TC9GWjhyRTVwa2JUM1hIalNzakUKLS0tIGdUSWZnRmhGNlBCWjF1VWR2QnZt
            YlI2cUY3dnI4Y2tsWURMN2RBcnVQQ3MK0t2bMqJWI+92oaKR9QaamfFmUvStENsG
            YbY1BpMkAnz9qrSTYucVaSdDQOXsnQIjD7ltgkbzFjkWfnj7n/iRLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T13:13:34Z"
    mac: ENC[AES256_GCM,data:tDD1HAyj7q91Nr0k0Vz1qDbPQalxS14cJbtyOi97cundYxivGseLvo5icb2QF1vRHiVM45kx1K0VKjxrjW1iwK1lK4TA47S/336neD9L3cQ3J7FNR+zAD3qBqVJAoXaFLVq4l7gLyf6ffOx6G820X8oGHG7tQ8pLCJjQBZqFhz8=,iv:K+V6DoCInBMBdbVRZv5oov/cdhkv+NrMospjYNxNAJY=,tag:KH5t8VLHZcTxvMnofNP0mQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
