persistence:
  enabled: true
  storageClassName: longhorn
  size: 5Gi

initChownData:
  enabled: false

securityContext:
  runAsNonRoot: true
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

admin:
  existingSecret: grafana-admin
  userKey: admin-user
  passwordKey: admin-password

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: infra-crowdsec-bouncer@kubernetescrd,infra-default-headers@kubernetescrd,infra-rate-limit@kubernetescrd
  hosts:
    - grafana.local.jabbas.dev
  tls:
    - secretName: infra-local-jabbas-dev-tls
      hosts:
        - grafana.local.jabbas.dev

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.infra.svc.cluster.local
        isDefault: true
        editable: false

grafana.ini:
  server:
    root_url: https://grafana.local.jabbas.dev
  security:
    allow_embedding: true
  auth.anonymous:
    enabled: true
    org_role: Viewer
