crowdsecBouncer:
    lapiKey: ENC[AES256_GCM,data:lTTljJuGpdcWX6S2baaXpH5OtjRQ0RHPAqBluthTR/rIPEazLAeMA25+LD5OZjq9Go7ApILWcG+6hZCGSXcvZA==,iv:zy1Y7O2fzAxmxmwaUgfYQKTCzYy0VI8vgxSs3X+orII=,tag:x883AeszxQAddflBf4MnoA==,type:str]
sops:
    age:
        - recipient: age1tneafc8h2ad3lmcvway7h5mrralurtuddqaahe3pz9jyhyhs7qxq5kjed7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RGtPOUdoS2hkeGduQWlJ
            UUVJeU9qTGY0d1lCTTA3ZWw2ZzBjektjV1NBClNxUFNnUWU0SlhsYkJtaGdwZWdV
            NW5jYk1IOWVmY296VVQxd0dsR2lSejAKLS0tIEF3eWovRlNuS2QyaExaczRlNEhY
            UDBQTGhkSDE0YndIQ0txbW5nTW1iTGcKZVW2lFv0sBfv/xh/Z7TeWpOc7yBcyySG
            WlvpX89t16wCIaiEoXlXoWm5/BOpTAS07iDk5JFQRX4vRYPIldpFaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T20:39:47Z"
    mac: ENC[AES256_GCM,data:pT3R2CiguFQNd6XaUlQbEmr+U7Rx4hCauE5yG95xcjIqdN7nCFAGEnSmih2/TTwCnEVHcuPP3ObzqBaUGTqnZ53GExMy0bZCQlClVfZvI/am5e7B8r6Kjyec5OyGZfgYkKNi64aUEJG6nEnjq4h9KXpaMo/U69vuETwjDDpns98=,iv:Cbx/8Ncu+l7nCcTr8DrQwJ9Qj1amSNE6W4ObPlE/5FU=,tag:tmw54X5x8BedzM4fI0UafQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
