crowdsecBouncer:
    lapiKey: ENC[AES256_GCM,data:gLO5rCtBDZJ1oeSZY3afJOMtYJZaFNfuQDwsaahNQPUIRZDv4S02LmNdvXKat9THNQw=,iv:NcvpEjkOpC/vQPJW+fyONS+iUVzeC2ZXZ1TqDAAjm3c=,tag:eXXgjyvM5LhJl4FpCOt4zw==,type:str]
sops:
    age:
        - recipient: age1tneafc8h2ad3lmcvway7h5mrralurtuddqaahe3pz9jyhyhs7qxq5kjed7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RGtPOUdoS2hkeGduQWlJ
            UUVJeU9qTGY0d1lCTTA3ZWw2ZzBjektjV1NBClNxUFNnUWU0SlhsYkJtaGdwZWdV
            NW5jYk1IOWVmY296VVQxd0dsR2lSejAKLS0tIEF3eWovRlNuS2QyaExaczRlNEhY
            UDBQTGhkSDE0YndIQ0txbW5nTW1iTGcKZVW2lFv0sBfv/xh/Z7TeWpOc7yBcyySG
            WlvpX89t16wCIaiEoXlXoWm5/BOpTAS07iDk5JFQRX4vRYPIldpFaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T15:40:09Z"
    mac: ENC[AES256_GCM,data:TbD08GlCjgl7/y3/G5gkiAWor3Lw6adglbSkiA8Odz7VYcDFpEKM73HegPdAK6JclnTeRuCr3sil0YUrvJ97yuC3SofjQMb1ii8gVTLvxTlEZ8F25tc4D+Dn9LxyBxphd7Kwp0semObw2GYQ7SzWuuJhoHutESgYA+0WqS0NX/M=,iv:/qRuYC3oQmjmiLsPYrBE3FXMcUiTsl3eUh8abp86N3w=,tag:go8AEH/2n5p6NpiYTdL15Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
