# To update qulity profiles run: sudo docker compose run --rm recyclarr sync

services:
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr:8.3.2@sha256:55afe316d3e4e4e3b9120cef7c79436b1b5311f6a18d4ef4b7653e720499c90a

    # Filesystem
    volumes:
      - ./config:/config
    read_only: true
    tmpfs: /tmp
    
    # Security
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true

    # Environment
    environment:
      TZ: ${TIMEZONE:-Europe/Stockholm}