# To update qulity profiles run: sudo docker compose run --rm recyclarr sync

services:
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr:8.6.0@sha256:3c38ceeb54438dd8327e4e65c9b48ba601a6d20fff833342d93c9b0bc4b1930b

    # Filesystem
    volumes:
      - ./config:/config
    read_only: true
    tmpfs: /tmp
    
    # Security
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true

    # Environment
    environment:
      TZ: ${TIMEZONE:-Europe/Stockholm}