# To update qulity profiles run: sudo docker compose run --rm recyclarr sync

services:
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr:8.5.1@sha256:734cecf44ae9be7cf0cb05b2c1bc7da0abef9d938cc11b605e58b3146205e5c0

    # Filesystem
    volumes:
      - ./config:/config
    read_only: true
    tmpfs: /tmp
    
    # Security
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true

    # Environment
    environment:
      TZ: ${TIMEZONE:-Europe/Stockholm}