# Verified working with rootless docker (docker compose up -d)

services:
  cloudflare-tunnel:
    container_name: cloudflare-tunnel
    image: cloudflare/cloudflared:latest
    restart: always

    command: tunnel --no-autoupdate run --token $CF_TOKEN

    # Security
    user: 1000:1000
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation

    # Environment
    environment:
      CF_TOKEN: ${CF_TOKEN}