# Verified working with rootless docker (docker compose up -d)

services:
  cloudflare-tunnel:
    container_name: cloudflare-tunnel
    image: cloudflare/cloudflared:2026.3.0@sha256:6b599ca3e974349ead3286d178da61d291961182ec3fe9c505e1dd02c8ac31b0
    restart: always

    command: tunnel --no-autoupdate run --token $CF_TOKEN

    # Security
    user: 1000:1000
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation

    # Environment
    environment:
      CF_TOKEN: ${CF_TOKEN}
