services:  
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:latest
    restart: unless-stopped

    # Networking
    ports:
      - 8080:8080
    
    # Filesystem
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - open-webui:/app/backend/data
    
    # Security
    user:
      - 1000:1000
    cap_drop:
      - ALL                      # drop all Linux capabilities
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation

    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      DATABASE_URL: ${DATABASE_URL}
      # ENABLE_IMAGE_GENERATION: True
      # IMAGE_GENERATION_ENGINE: comfyui
      # COMFYUI_BASE_URL: ${COMFYUI_BASE_URL}
      # COMFYUI_WORKFLOW: ${COMFYUI_WORKFLOW}
      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: searxng
      RAG_WEB_SEARCH_RESULT_COUNT: 3
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 5
      SEARXNG_QUERY_URL: ${SEARXNG_BASE_URL}/search?q=<query>
    
    depends_on:
      - database



  # Database for open web ui
  database:
    container_name: database
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped

    # Filesystem
    volumes:
      - database:/var/lib/postgresql/data
    
    # Security
    cap_drop:
      - ALL                      # drop all Linux capabilities
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation

    # Environment
    environment:
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}



volumes:
  database:
    driver: local