# Verified working with rootfull docker (run with sudo docker compose up -d)

services:
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped

    # Networking
    network_mode: "container:gluetun"
    
    # Filesystem
    volumes:
      - ./config:/config
      - /mnt/data/media:/data/media
    
    # Security
    security_opt:
      - no-new-privileges:true

    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

    

    
