alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

prometheus-node-exporter:
  enabled: false

server:
  fullnameOverride: prometheus-server
  baseURL: https://prometheus.local.jabbas.dev
  retention: 15d
  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 65534
    fsGroup: 65534
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

  persistentVolume:
    enabled: true
    storageClass: longhorn
    size: 20Gi

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: infra-ui-default@kubernetescrd
    hosts:
      - prometheus.local.jabbas.dev
    tls:
      - secretName: infra-local-jabbas-dev-tls
        hosts:
          - prometheus.local.jabbas.dev

extraScrapeConfigs: |
  - job_name: proxmoxhost
    scheme: https
    static_configs:
      - targets:
          - stratton-prometheus-node.local.jabbas.dev

configmapReload:
  prometheus:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
