services:
  nextcloud:
    container_name: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest
    restart: unless-stopped

    # Networking
    ports:
      - 4443:443

    # Filesystem
    volumes:
      - ./config:/config
      - /mnt/data/nextcloud:/data

    # Security
    security_opt:
      - no-new-privileges:true   # forbid privilege escalation
    
    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"