upstream:
    authentik:
        secret_key: ENC[AES256_GCM,data:iAMhmWmj9c8HfvmqU1MrYeylH9CVMTjDCidK22B8sTjqySka5WFtTVuJuLio7GzaFe5AIn3da1OWUbPyiF8/97K+wrqJ/w==,iv:BDKQUqcEyT+/hiQLNXzi1CAHqlNKx6HDITlCnwK6c+Y=,tag:v3Rjjm1n6SUkQWuXUsSKaA==,type:str]
sops:
    age:
        - recipient: age1tneafc8h2ad3lmcvway7h5mrralurtuddqaahe3pz9jyhyhs7qxq5kjed7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWWhPVXVRNHh1cXpNSkhQ
            SHl0aUtuVjV4TE5MZDh2cEkxYzdiT3FSOGhzCmxXeGRsY0E3T2VhYmxQa1JOa3NW
            NDZJL0d5NmJrdDNYWEt0YWxhR1I3bU0KLS0tIEp5ZStIcHVyNnoyWkwraHVrenJp
            ZEY0OFJKUDY4WXJRaEgvcWVjTXh6SEEKyGSbs8SCfZ2pq2FaV17dw7sO2tmKweZ1
            CQJUtZiJxYgdsx/841lLk2GkLr+qPV1ckWjf7HnMG1JjY7DtIhbA+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T09:58:25Z"
    mac: ENC[AES256_GCM,data:MJulTPUFjpzARVzGrCoYFZ5yeUyEN/6F1fxuF+7blRagEC0RsBpEdqT78D4pOAiBEp8yP9TLPJ+gNoRS1cq1DhnJeIdZxe93nb+RjMMHYNc2ZPamCHmP1wCqKQaE9/WhFn27sidaCwVA6L7LgZKcPh31yCbqtykzwou7srXUcT4=,iv:uNwN9fQG9+ccsyZs4669wxXN/e4mYWHzq8FlLcY4hFw=,tag:FkSxw1r8Ckb2hBcoC1fuWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
