apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: cluster-core
  sources:
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: 1.19.2
      helm:
        releaseName: cilium
        valueFiles:
          - $values/machines/stratton/k8s/workloads/cluster/cilium/values.yaml
    - repoURL: https://github.com/jabb4/home-server.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/jabb4/home-server.git
      targetRevision: main
      path: machines/stratton/k8s/workloads/cluster/cilium/resources
      helm:
        releaseName: cilium-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
