- Infrastructure:
      - Unifi:
            href: https://unifi.local.jabbas.dev/network/default/dashboard
            icon: unifi.png
            siteMonitor: https://unifi.local.jabbas.dev

      - Pi-hole:
            href: https://pi-hole.local.jabbas.dev
            icon: pi-hole.png
            siteMonitor: https://pi-hole.local.jabbas.dev

      - Traefik:
            href: https://traefik-rocky.local.jabbas.dev/dashboard/
            icon: traefik.png
            siteMonitor: https://traefik-rocky.local.jabbas.dev/dashboard/

      - Dockhand:
            href: https://dockhand.local.jabbas.dev
            icon: docker.png
            siteMonitor: https://dockhand.local.jabbas.dev

      - PiKVM:
            href: https://pikvm.local.jabbas.dev
            icon: pikvm.png
            siteMonitor: https://pikvm.local.jabbas.dev

      - Proxmox:
            href: https://pve.local.jabbas.dev
            icon: proxmox.png
            siteMonitor: https://pve.local.jabbas.dev

      - TrueNAS:
            href: https://truenas.local.jabbas.dev
            icon: truenas.png
            siteMonitor: https://truenas.local.jabbas.dev



- Streaming:
      - Seerr:
            href: https://seerr.local.jabbas.dev
            icon: seerr.png
            siteMonitor: https://seerr.local.jabbas.dev

      - Jellyfin:
            href: https://jellyfin.local.jabbas.dev
            icon: jellyfin.png
            siteMonitor: https://jellyfin.local.jabbas.dev

      - SABnzbd:
            href: https://sabnzbd.local.jabbas.dev
            icon: sabnzbd.png
            siteMonitor: https://sabnzbd.local.jabbas.dev

      - Radarr:
            href: https://radarr.local.jabbas.dev
            icon: radarr.png
            siteMonitor: https://radarr.local.jabbas.dev

      - Sonarr:
            href: https://sonarr.local.jabbas.dev
            icon: sonarr.png
            siteMonitor: https://sonarr.local.jabbas.dev

      - Prowlarr:
            href: https://prowlarr.local.jabbas.dev
            icon: prowlarr.png
            siteMonitor: https://prowlarr.local.jabbas.dev

      - Bazarr:
            href: https://bazarr.local.jabbas.dev
            icon: bazarr.png
            siteMonitor: https://bazarr.local.jabbas.dev



- Home Automation:
      - Home-Assistant:
            href: https://home-assistant.local.jabbas.dev
            icon: home-assistant.png
            siteMonitor: https://home-assistant.local.jabbas.dev
            widget:
                  type: homeassistant
                  url: https://home-assistant.local.jabbas.dev
                  key: {{HOMEPAGE_VAR_HOMEASSISTANT_API}}
                  custom:
                        - state: sensor.server_rack_plug_power
                          label: Server rack power draw
