backups:
    enabled: ENC[AES256_GCM,data:wvc8/Cc=,iv:60LSSk27/NsGmWmbuaTPTeweRSD/4Xs/v92/HOdRMOY=,tag:a2c0QtO46atmvXCrhDd6Zg==,type:bool]
backupTarget:
    credentials:
        accessKeyId: ENC[AES256_GCM,data:utYNv7sp+R7egk3f/GLSjPv4wX4w2irWNII=,iv:gIol6gIjAU07/jbliOtMadV4WwgbQaso9cpTsXzyEow=,tag:dcM5TCRK18hEByLz3d4+aA==,type:str]
        secretAccessKey: ENC[AES256_GCM,data:8rthInKoSRcMIA86G6t8rAginu3B3Ufved2PRDpx,iv:M7AmCk7tVw7eLSjzaalekg6HYDfrxTfVaW7Rb/iCpIw=,tag:dN9nMRIy29TjImMuBYSP6Q==,type:str]
        endpoint: ENC[AES256_GCM,data:CHoqi9ciDwZ37FxHafiinE97kSe2WFMkLhNCbyN4iHo=,iv:7VAIEnsT04nUoXyxQ62cFOVSCXWOy3Rpt52PpDefWW8=,tag:riRaIAfDmaIUupx302j9vQ==,type:str]
        cert: ""
        virtualHostedStyle: ENC[AES256_GCM,data:jdJ3pNk=,iv:LlvS2Dnduw38anDwt/BHXqj2+mgjvR9Ib4ZbhHVT+t4=,tag:LmYAdQnCn/cdueTJjyplxA==,type:bool]
encryption:
    globalKey:
        value: ENC[AES256_GCM,data:j7mlqfvzawJmWRbKYNxaMnnkcVKFrKwVpj+sH+/eFLNYlsrNN6vD0dVzbsefJ5sT3THcgdMzWWTdB9lEX/KfW6j/H9VrU8zbZPJjjQzvj8EhnCaFAlhQOw==,iv:gZW0zZeOCz43DPIjS2acpkaZoHXHrs72x01K/3w9660=,tag:egJ88nVTUngsS7luKbh+Hw==,type:str]
sops:
    age:
        - recipient: age1tneafc8h2ad3lmcvway7h5mrralurtuddqaahe3pz9jyhyhs7qxq5kjed7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSnJIdTR1VWVUVTg1WkpT
            T1RMdXF1ZytXYmJGTXd4WjRvcnFlWGFqY2hNClk2cjJRZHhGUE5oV0JTSWYrVEl2
            ZFRrMVlLQ3FyQ2l0eUMzWEk0emVLNTQKLS0tIFA3QitVSFB2Y3BXeUJ6V1Z2V0Q5
            ck1TajFwdFE5aVZNaG5wUWtnNWFXd1EK+6R3w5TwMlPcoOV17/gesQ9LqgApDjp2
            eJTiOvmsn3OA6o9l7To/EoQM0UY3quJDqR7FbLnIhzqjy5KtNxmlJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T13:51:10Z"
    mac: ENC[AES256_GCM,data:ZcL+lHOPICxUD/EboY0pVJ8S3UI5+Vza+FEGJUhf0A4QGNVVabLIUZ22NZFXsPr6R40b9s1ha5rt0P8I/Z2VKG7EXxJZ711+IP7dgKKgv8ykoj1w23h1/n6phJvyi55vvR7HeUc41QQslSYh5Xn8CI4H0qgJxfJYopBuuJtHm0w=,iv:720YjU29ZU8B5pMNKwTg7aLfeUPuv5FeijjFnJVQ4Hw=,tag:8s/VGWXzHUqUJqSfs3FDPw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
