# Verified working with rootless docker

services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped

    # Networking
    ports:
      - 3001:3000

    # Filesystem
    volumes:
      - ./config:/app/config

    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation
    
    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      HOMEPAGE_ALLOWED_HOSTS: homepage.local.jabbas.dev
      HOMEPAGE_VAR_PROXMOX_API_USERNAME: ${HOMEPAGE_VAR_PROXMOX_API_USERNAME}
      HOMEPAGE_VAR_PROXMOX_API_PASSWORD: ${HOMEPAGE_VAR_PROXMOX_API_PASSWORD}
      HOMEPAGE_VAR_QBITTORRENT_USERNAME: ${HOMEPAGE_VAR_QBITTORRENT_USERNAME}
      HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ${HOMEPAGE_VAR_QBITTORRENT_PASSWORD}
      HOMEPAGE_VAR_PIHOLE_API: ${HOMEPAGE_VAR_PIHOLE_API}
      HOMEPAGE_VAR_AUTHENTIK_API: ${HOMEPAGE_VAR_AUTHENTIK_API}
      HOMEPAGE_VAR_UNIFI_USERNAME: ${HOMEPAGE_VAR_UNIFI_USERNAME}
      HOMEPAGE_VAR_UNIFI_PASSWORD: ${HOMEPAGE_VAR_UNIFI_PASSWORD}
      HOMEPAGE_VAR_JELLYFIN_API: ${HOMEPAGE_VAR_JELLYFIN_API}
      HOMEPAGE_VAR_SONARR_API: ${HOMEPAGE_VAR_SONARR_API}
      HOMEPAGE_VAR_RADARR_API: ${HOMEPAGE_VAR_RADARR_API}
      HOMEPAGE_VAR_PROWLARR_API: ${HOMEPAGE_VAR_PROWLARR_API}
      HOMEPAGE_VAR_TRUENAS_API: ${HOMEPAGE_VAR_TRUENAS_API}
      HOMEPAGE_VAR_READARR_API: ${HOMEPAGE_VAR_READARR_API}
      HOMEPAGE_VAR_BAZARR_API: ${HOMEPAGE_VAR_BAZARR_API}
      HOMEPAGE_VAR_HOMEASSISTANT_API: ${HOMEPAGE_VAR_HOMEASSISTANT_API}
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
