apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  bookmarks.yaml: |
{{ .Files.Get "files/config/bookmarks.yaml" | indent 4 }}
  custom.css: |
{{ .Files.Get "files/config/custom.css" | indent 4 }}
  custom.js: |
{{ .Files.Get "files/config/custom.js" | indent 4 }}
  docker.yaml: |
{{ .Files.Get "files/config/docker.yaml" | indent 4 }}
  kubernetes.yaml: |
{{ .Files.Get "files/config/kubernetes.yaml" | indent 4 }}
  proxmox.yaml: |
{{ .Files.Get "files/config/proxmox.yaml" | indent 4 }}
  services.yaml: |
{{ .Files.Get "files/config/services.yaml" | indent 4 }}
  settings.yaml: |
{{ .Files.Get "files/config/settings.yaml" | indent 4 }}
  widgets.yaml: |
{{ .Files.Get "files/config/widgets.yaml" | indent 4 }}
