{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "homepage-secrets" | quote }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secret.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
