# Verified working with rootfull docker (run with sudo docker compose up -d)

services:
  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    restart: unless-stopped

    # Networking
    network_mode: "container:gluetun"

    # Filesystem
    volumes:
      - ./config:/config
      - /mnt/data/usenet:/data/usenet:rw
    
    # Security
    security_opt:
      - no-new-privileges:true

    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"