dashboard:
    basicAuthUsers: ENC[AES256_GCM,data:3vs2Q8qMb3S/LeNHILBUyrLtGdx6pu6Mn/EIb0TOKs/r9Erh6Z3P3BOiXwD4S7HUsv2ilLobaLJtwSzfQv/lPa68,iv:nCUp/T7hUORhTAJEZpEFOC/dfkoVnuFd92mPGelRUnU=,tag:rx1dhz1UENhF6EXA9IGSiA==,type:str]
crowdsecBouncer:
    lapiKey: ENC[AES256_GCM,data:BroVI2MNJdo3uJUdGrvCXNA/hkC9Mto4AlOkCPal0SMMaWL0GRZ/b0VCbqpPn818T6o=,iv:JK1d/BKDWaoJ4eK9RaF/mWKWhBjq1YY8fmYcBz34ttc=,tag:kJmpY9K31c6q+Lj1M1gO8g==,type:str]
sops:
    age:
        - recipient: age1tneafc8h2ad3lmcvway7h5mrralurtuddqaahe3pz9jyhyhs7qxq5kjed7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NmRPNmZuY0VuRmZYdG5Q
            bXd6MWsyd250cENIeFBXZE9EeHQ1RVcvT0Q4Cm01S3dCSFVYRVRGWmdhSFVnNlpo
            UWJMdUxvK3d0bUN5cHBMSGpkU3FaZjgKLS0tIEh1TUpuc3lEUFdaVkNrcDFFemdu
            a1p4YnRkRVhYbUlGMk9HaVdkMFhKdTgKrBsOJB/KXK7W1TwpGmimsH+KfQ/WCd61
            U1Z+HPC5jsBq1PXUmPBqQwc/stpElWdQgCJuOJduESm3AANmsFIOEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T17:18:37Z"
    mac: ENC[AES256_GCM,data:3STtt2oixFII+5V8y2JBkJb1Sr+o3Jrby9as3dcmIwH29EL4PevneVz1oLfybL5PatzoZXqp0BvWm9saW5UTsDZwLBfxb8vEAIgpYAjDzN3BRnUZVujGh6YZ0rBVCc74OOSZi4VRjU2GBYMbbl0FXLJWkLpGm/vLoY+S9eLHA04=,iv:8hTG0+jf0I5Tg8lMG1Y9UTaC6+58BTggWsFP5ZsK9AQ=,tag:A46hZuX5HLN4tzjBicr81w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
