dashboard:
    basicAuthUsers: ENC[AES256_GCM,data:RcXe8rCMlZtoBajPTyC1d4x+U5zsW9/nT6wx3M+QvWQNIyRBeFeK8hNBOG9DqVvMYIXAI7KmCWMfG6fMIw5E5X8j,iv:K7T5dJfYDic7QKRG9FF6IQ/GHC/U9MHjhoxb6D1nkBI=,tag:YN8CWwcXoDDhESNfUppYPg==,type:str]
sops:
    age:
        - recipient: age1tneafc8h2ad3lmcvway7h5mrralurtuddqaahe3pz9jyhyhs7qxq5kjed7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa0tVT2xoT2l2Y2JyR3lN
            RGtnUjRHVVFrSVJYYmhkOFprdFRWMUhmbVJZCloycGFSMUV5KzJZZVIwSFRWUmM4
            R1FFSDk5N1RQaE5MZkNudFpmV2tLMG8KLS0tIGU3OWFLLzY0OCt2cisycnNmdmw1
            WFNRYlYzMlpxbVJmZVpPaCtJUjFQZWMKwMR72GyqolAQQnybgD6oxH4AAkxa2wzy
            psTNVnKMQerpHg9cLupCJxoaSmhmJQ7aNZPFw07dam+uHV72Sa/Iww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T15:35:47Z"
    mac: ENC[AES256_GCM,data:peMtaU0Q6G9Ow6xrkBTuoe9JdwWIPL2tPHprO3CquQMS+mg6tpQ1QHIzalEqF8s8hcuO3FOnAbibshjM4nd1uh8ECAOspjlSmzmc3N5NZ4KhlJVpa711N1mLYbRpcwZshWttVvF3w7Dlbe7hbwCTy4eBRiCQDOFcWOy9ZuNlhwA=,iv:a64gOAuX6YHo1oDTQ7d0h3WPMIlG8AsgkpQzFuPGrvw=,tag:i4cnz/LDVJ2eQIqIvfGRbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
