dashboard:
    basicAuthUsers: ENC[AES256_GCM,data:F4QPbxCJ11ahqhAw2UuOxgIV9SbAd02mGbltxW3BaQ==,iv:BoM6J3fMObvjjWrhfT4J+JQLdc4ZFek+AFsHX3rlk5k=,tag:qyggv1wa4o1z7WlFWYyrtw==,type:str]
sops:
    age:
        - recipient: age1tneafc8h2ad3lmcvway7h5mrralurtuddqaahe3pz9jyhyhs7qxq5kjed7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa0tVT2xoT2l2Y2JyR3lN
            RGtnUjRHVVFrSVJYYmhkOFprdFRWMUhmbVJZCloycGFSMUV5KzJZZVIwSFRWUmM4
            R1FFSDk5N1RQaE5MZkNudFpmV2tLMG8KLS0tIGU3OWFLLzY0OCt2cisycnNmdmw1
            WFNRYlYzMlpxbVJmZVpPaCtJUjFQZWMKwMR72GyqolAQQnybgD6oxH4AAkxa2wzy
            psTNVnKMQerpHg9cLupCJxoaSmhmJQ7aNZPFw07dam+uHV72Sa/Iww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T21:31:34Z"
    mac: ENC[AES256_GCM,data:HYDJWivsOr1YB6U7XLN18lNy/ylSxfT+eyV6C8Jnk8gT+FmcO4g42TQkD72XFo1m+f/cdRBBP42j4WUTzDcF6uXZ0akL5AwvQqWQ3fBfM76lolmCShCWoY4aZwyNlN+70B8MD8zq/B1i7jcFxtXVy0my0Bu2vPrTTHEY5+xMY34=,iv:8V+K0J2JCVLe09teWg0rpxhbpOj1SnbTAD6mgGMGexg=,tag:ps5pIeIyvPKD27Imd+ZN2A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
