{{- $adminPassword := required "adminPassword is required" .Values.adminPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: infra
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
type: Opaque
stringData:
  admin-user: admin
  admin-password: {{ $adminPassword | quote }}
