adminPassword: ENC[AES256_GCM,data:YVGVlHMQ8JZWCDo0gb9zLoxzp/uiN1oiOfIreyKyu6hDYbZww4hSfvAEF9Wc/0dUh1s=,iv:KXB1M6lO6nnw08T1wqAfYzgaggr4vl5AEVqQhBMg1WI=,tag:NBAj4TzqE0SGpLMYudSLHg==,type:str]
sops:
    age:
        - recipient: age1tneafc8h2ad3lmcvway7h5mrralurtuddqaahe3pz9jyhyhs7qxq5kjed7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UlpoenF5SS8ydHhNcGU2
            dG5GeWxhSDAxaFRyT280UkFMSERkM1ZjemhJCnVhQjlvbi9pZ3VocGE2UXlBV1ZZ
            YjN4TC9GWjhyRTVwa2JUM1hIalNzakUKLS0tIGdUSWZnRmhGNlBCWjF1VWR2QnZt
            YlI2cUY3dnI4Y2tsWURMN2RBcnVQQ3MK0t2bMqJWI+92oaKR9QaamfFmUvStENsG
            YbY1BpMkAnz9qrSTYucVaSdDQOXsnQIjD7ltgkbzFjkWfnj7n/iRLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T15:37:39Z"
    mac: ENC[AES256_GCM,data:F2nMjBwp75AD+OHFAnLKuVgt9G37Enr7Y3xJgErYr3EqCuJVfzf/aTUnYOTtLNl372OUTbHyVuSXbqGeJU9VswDrm8oFvSnoZBK86U5/YpVOPFstySOFK5zqQ00dZmOFbHv+oirbsEHa/0ID250CZ9tetb7gjPgNs8V9P1urDAA=,iv:+EoTyTE1PfR5E16sntTXN6UYxe3f6wshSmRkN62Q0cc=,tag:3GnKNXYNE4jzfp65V3G45w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
