apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: cluster-core
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.11.1
      helm:
        releaseName: longhorn
        valueFiles:
          - $values/machines/stratton/k8s/workloads/cluster/longhorn/values.yaml
          - secrets://$values/machines/stratton/k8s/workloads/cluster/longhorn/resources/secrets.sops.yaml
    - repoURL: https://github.com/jabb4/home-server.git
      targetRevision: v2
      ref: values
    - repoURL: https://github.com/jabb4/home-server.git
      targetRevision: v2
      path: machines/stratton/k8s/workloads/cluster/longhorn/resources
      helm:
        releaseName: longhorn-resources
        valueFiles:
          - secrets://secrets.sops.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
