global:
  timezone: Europe/Stockholm

service:
  ui:
    type: ClusterIP

persistence:
  defaultClass: false
  defaultClassReplicaCount: 1
  reclaimPolicy: Retain

preUpgradeChecker:
  jobEnabled: false

csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

defaultSettings:
  allowRecurringJobWhileVolumeDetached: true
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /var/mnt/longhorn
  defaultReplicaCount: '{"v1":"1","v2":"1"}'
  replicaAutoBalance: disabled
  restoreVolumeRecurringJobs: true
