services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:v1.12.3@sha256:cc84f2f5eb3c7734353701ccbaa24ed02dacb0d119114e50e4251e2005f3990a
    restart: unless-stopped
    ports:
      - 127.0.0.1:3001:3000
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: ${TIMEZONE:-Europe/Stockholm}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      LOG_TARGETS: stdout
      HOMEPAGE_ALLOWED_HOSTS: homepage.local.jabbas.dev,127.0.0.1:3001,localhost:3001
      HOMEPAGE_VAR_AUTHENTIK_API: ${HOMEPAGE_VAR_AUTHENTIK_API:-}
      HOMEPAGE_VAR_BAZARR_API: ${HOMEPAGE_VAR_BAZARR_API:-}
      HOMEPAGE_VAR_HOMEASSISTANT_API: ${HOMEPAGE_VAR_HOMEASSISTANT_API:-}
      HOMEPAGE_VAR_JELLYFIN_API: ${HOMEPAGE_VAR_JELLYFIN_API:-}
      HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY: ${HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY:-}
      HOMEPAGE_VAR_PIHOLE_PASSWORD: ${HOMEPAGE_VAR_PIHOLE_PASSWORD:-}
      HOMEPAGE_VAR_PROWLARR_API: ${HOMEPAGE_VAR_PROWLARR_API:-}
      HOMEPAGE_VAR_PROXMOX_API_PASSWORD: ${HOMEPAGE_VAR_PROXMOX_API_PASSWORD:-}
      HOMEPAGE_VAR_PROXMOX_API_USERNAME: ${HOMEPAGE_VAR_PROXMOX_API_USERNAME:-}
      HOMEPAGE_VAR_RADARR_API: ${HOMEPAGE_VAR_RADARR_API:-}
      HOMEPAGE_VAR_SABNZBD_API_KEY: ${HOMEPAGE_VAR_SABNZBD_API_KEY:-}
      HOMEPAGE_VAR_SONARR_API: ${HOMEPAGE_VAR_SONARR_API:-}
      HOMEPAGE_VAR_TRUENAS_API: ${HOMEPAGE_VAR_TRUENAS_API:-}
      HOMEPAGE_VAR_UNIFI_PASSWORD: ${HOMEPAGE_VAR_UNIFI_PASSWORD:-}
      HOMEPAGE_VAR_UNIFI_USERNAME: ${HOMEPAGE_VAR_UNIFI_USERNAME:-}
      HOMEPAGE_VAR_WEATHERAPI_API_KEY: ${HOMEPAGE_VAR_WEATHERAPI_API_KEY:-}
    volumes:
      - ./config:/app/config
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
