services:  
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      DATABASE_URL: ${DATABASE_URL}
      # ENABLE_IMAGE_GENERATION: True
      # IMAGE_GENERATION_ENGINE: comfyui
      # COMFYUI_BASE_URL: ${COMFYUI_BASE_URL}
      # COMFYUI_WORKFLOW: ${COMFYUI_WORKFLOW}
      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: searxng
      RAG_WEB_SEARCH_RESULT_COUNT: 3
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 5
      SEARXNG_QUERY_URL: ${SEARXNG_BASE_URL}/search?q=<query>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./open-webui:/app/backend/data
    depends_on:
      - database
    extra_hosts:
      - host.docker.internal:host-gateway

  # Database for open web ui
  database:
    image: docker.io/library/postgres:16-alpine
    container_name: database
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}

volumes:
  database:
    driver: local