services:
  model-downloader:
    container_name: model-downloader
    build: ./comfy-ui/services/download/
    image: comfy-download
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./comfy-ui/data:/data

  comfy-ui:
    container_name: comfy-ui
    build: ./comfy-ui/services/comfy/
    image: comfy-ui
    ports:
      - 7860:7860
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      CLI_ARGS:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./comfy-ui/data:/data
      - ./comfy-ui/output:/output
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ compute, utility ]
    restart: unless-stopped