{{- $lapiKey := required "crowdsecBouncer.lapiKey is required" .Values.crowdsecBouncer.lapiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.lapiBouncers.secretName | quote }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
type: Opaque
stringData:
  BOUNCER_KEY_traefik: {{ $lapiKey | quote }}
