services:  
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    ports:
      - 8081:8080
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      SEARXNG_BASE_URL: ${SEARXNG_BASE_URL}
      UWSGI_WORKERS: ${SEARXNG_UWSGI_WORKERS:-4}
      UWSGI_THREADS: ${SEARXNG_UWSGI_THREADS:-4}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./searxng:/etc/searxng
    restart: unless-stopped