services:  
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    depends_on:
      - database

    # Networking
    ports:
      - 3000:8080
    
    # Filesystem
    volumes:
      - open-webui:/app/backend/data
    
    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation

    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      DATABASE_URL: ${DATABASE_URL}
      # ENABLE_IMAGE_GENERATION: True
      # IMAGE_GENERATION_ENGINE: comfyui
      # COMFYUI_BASE_URL: ${COMFYUI_BASE_URL}
      # COMFYUI_WORKFLOW: ${COMFYUI_WORKFLOW}
      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: searxng
      RAG_WEB_SEARCH_RESULT_COUNT: 3
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
      SEARXNG_QUERY_URL: https://${SEARXNG_HOSTNAME}/search?q=<query>
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"



  # Database for open web ui
  database:
    container_name: database
    image: docker.io/library/postgres:17-alpine
    restart: unless-stopped

    # Filesystem
    volumes:
      - database:/var/lib/postgresql/data
    
    # Security
    security_opt:
      - no-new-privileges:true  # forbid privilege escalation

    # Environment
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-Europe/Stockholm}

      # Service specific
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"