acme:
    email: ENC[AES256_GCM,data:2VLVOSxdOQADL28HYpAMfo6utfsXDho=,iv:myYXU/ED1PBXwTVjLg6Dh+Qp0wSJzDzeYNWoBbLgsHQ=,tag:E89xIRkLCBpNrttmFUoCiw==,type:str]
cloudflare:
    apiToken: ENC[AES256_GCM,data:MLE8pibIygPgzruUbG2Rp/cvZcvNXhDd/4sZ+mY=,iv:i4GHe3Sm/hvPf96A7zeaMjRxHYvVtGj/gb0F4BgUAWo=,tag:+wjRIbqQiXElWWD1+QpW7Q==,type:str]
sops:
    age:
        - recipient: age1tneafc8h2ad3lmcvway7h5mrralurtuddqaahe3pz9jyhyhs7qxq5kjed7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRTUxTTRWMmlWK1p0S0Q2
            Uml6Y3FQUlJuSFNBWWdhcllHUllCUXQ5c1VjCnJWZHBrMDR5WnM4UDdVUkNFMkdH
            MHRXS296YU1SVnFmUWNocEZDYXliT2cKLS0tIHJnejAxTEY2V1ZWT1hyaDl5RDFM
            YTdlNUxwSkxPOVJMVVlFcFI5ZWxrQjgKEK+EQ1z6E4JOrbvhAu7jk+Kg0uKE4zss
            8Cm4RBjFmAlJNrOE1bkFKgnSjVPbGhhIDImB151mGXn+a6jB+BmoPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T21:31:34Z"
    mac: ENC[AES256_GCM,data:xO3DV8rW0urMxMK4/PWrXCO1Lx5X7YsLVC0fqmYKLHe6p8oK+2ach5eF1Sa3dWxcVbXQAozZuosLyM/02GGcvKW+RZkSqCzF43lAvBniKgSpwo3N7L53BtUa1FIUi07qlXGywQa9Ho7ZNPuf2i0JWc8MzyOPzJzC+YFdaGPVIj4=,iv:usqmumSZZ2sB/9mN0fCQuVYLySbRegTdyJoLh2G+qYI=,tag:rAAlq5mTt1IGMpwboGUX7g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
