acme:
    email: ENC[AES256_GCM,data:sBMboW8tdkRzHuAjZtoxMATFfvBQ6HvQM0DayRpW,iv:xHsWi4M9//3coLvYAZ52Fi613tF/fC3kAJCp7PlzkDI=,tag:X5mXC5HZCHIbvJoraGF8NQ==,type:str]
cloudflare:
    apiToken: ENC[AES256_GCM,data:GvMJQ+IFRKRcZhMOok3cXo/gMYUN7nUf/tJmgxEx59a7V3rNgGlaYA==,iv:2z5T/3hTSJAYODfesyjMXf+ZFUXBseTdH2Q+d7UY4MA=,tag:Ze5Q0o4M2iAE4uFS5mZ+ZQ==,type:str]
sops:
    age:
        - recipient: age1tneafc8h2ad3lmcvway7h5mrralurtuddqaahe3pz9jyhyhs7qxq5kjed7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRTUxTTRWMmlWK1p0S0Q2
            Uml6Y3FQUlJuSFNBWWdhcllHUllCUXQ5c1VjCnJWZHBrMDR5WnM4UDdVUkNFMkdH
            MHRXS296YU1SVnFmUWNocEZDYXliT2cKLS0tIHJnejAxTEY2V1ZWT1hyaDl5RDFM
            YTdlNUxwSkxPOVJMVVlFcFI5ZWxrQjgKEK+EQ1z6E4JOrbvhAu7jk+Kg0uKE4zss
            8Cm4RBjFmAlJNrOE1bkFKgnSjVPbGhhIDImB151mGXn+a6jB+BmoPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T15:33:35Z"
    mac: ENC[AES256_GCM,data:nVx1gYzejwXdwPMEZPEk93Hu0UBM46gst40Ur6R9tOTHAK7uEpsUVEGakDQU3D6IMYaInMpTHe4KMx1t1mx5ZN1nfzmW9v8N9IMUSfcxXxZYFGJsa73yFNFrbtu8cmggnsY5hGpJYWKdnDstqmUBirzOZDunP2cDfLTdeaM6oFc=,iv:epZPdk4besmtbjxbGqeEZr2417M6nMWqokWmsDniiL0=,tag:za53VzyMkfcWpp/CnZF9Yg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
