# To update qulity profiles run: sudo docker compose --rm recyclarr sync

services:
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr

    # Filesystem
    volumes:
      - ./config:/config
    read_only: true
    tmpfs: /tmp
    
    # Security
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true

    # Environment
    environment:
      TZ: ${TIMEZONE:-Europe/Stockholm}
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"