{{- range .Values.apps }}
{{- $appSecrets := index $.Values.appSecrets .name | default dict -}}
{{- $password := required (printf "appSecrets.%s.password is required" .name) (get $appSecrets "password") -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName | quote }}
  namespace: infra
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: {{ .username | quote }}
  password: {{ $password | quote }}
{{- if ne .namespace "infra" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName | quote }}
  namespace: {{ .namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
type: kubernetes.io/basic-auth
stringData:
  username: {{ .username | quote }}
  password: {{ $password | quote }}
{{- end }}
{{- end }}
